### ISSUE TITLE
Crash when clicking mirror buttons with no image selected

### ISSUE THREAD

**Issue by mmallet-youilabs** [krsteeve/EmojiWorkflow#6]
Repo steps:
- open workflow app in fresh browser tab
- click Mirror Right (or Mirror Left)

Expected:
- nothing happens

Actual:
- app crashes (white browser screen)

Double plus P0 purple priority, this is blocking client release for customer trials

**Comment by mmallet-youilabs** [comment]
actually that happens when using any of the controls when there's no image selected

**Comment by krsteeve** [comment]
Resolved: https://github.com/krsteeve/EmojiWorkflow/commit/c9766caeb14b25ce726c57808f62654ca08f7715
